#!/usr/bin/env python3
"""
Replay Primitive-Planner scenario_data.json in the NavRL Isaac Sim / OmniDrones stack.

This script is additive: it does not modify NavRL environment code.
It loads the JSON scene generated by Primitive-Planner, spawns static box obstacles,
creates one OmniDrones multirotor per valid trajectory, and tracks the logged path
with LeePositionController.

Example:
  /home/haoyus/projects/NavRL/isaac-sim/python.sh \
    /home/haoyus/projects/NavRL/NavRL-code/NavRL/isaac-training/training/scripts/scenario_json_replay.py \
    --json /abs/path/to/scenario_data.json

  /home/haoyus/projects/NavRL/isaac-sim/python.sh \
    /home/haoyus/projects/NavRL/NavRL-code/NavRL/isaac-training/training/scripts/scenario_json_replay.py \
    --config /home/haoyus/projects/NavRL/NavRL-code/NavRL/isaac-training/training/cfg/train.yaml \
    --json /abs/path/to/scenario_data.json

Notes:
- Tested for the NavRL layout that vendors OmniDrones and Orbit under `isaac-training/third_party`.
- The script uses the same Hummingbird multirotor class NavRL trains with by default.
- Obstacles are visualized as static cuboids; drones are physically simulated and
  commanded to track the reference path.
"""

from __future__ import annotations

import argparse
import datetime
import json
import math
import os
import sys
from pathlib import Path

import numpy as np
import torch


SCRIPT_DIR = Path(__file__).resolve().parent
TRAINING_DIR = SCRIPT_DIR.parent
ISAAC_TRAINING_DIR = TRAINING_DIR.parent
THIRD_PARTY_DIR = ISAAC_TRAINING_DIR / "third_party"
OMNIDRONES_DIR = THIRD_PARTY_DIR / "OmniDrones"
ORBIT_SOURCE_DIR = THIRD_PARTY_DIR / "orbit" / "source"

for path in (SCRIPT_DIR, TRAINING_DIR, OMNIDRONES_DIR):
    path_str = str(path)
    if path_str not in sys.path:
        sys.path.insert(0, path_str)
for ext_dir in ORBIT_SOURCE_DIR.glob("extensions/*"):
    path_str = str(ext_dir)
    if path_str not in sys.path:
        sys.path.insert(0, path_str)


DEFAULT_ARGS = {
    "config": None,
    "json": None,
    "headless": False,
    "speed": 1.0,
    "loop": False,
    "anti_aliasing": 4,
    "drone_model": "Hummingbird",
    "sim_dt": 0.01,
    "ground_size": 120.0,
    "camera_mode": "fit_topdown",
    "camera_margin": 1.12,
    "camera_fov_deg": 60.0,
    "camera_eye": (0.0, 2.5, 24.0),
    "camera_lookat": (0.0, 2.5, 0.0),
    "resolution": (2560, 1440),
    "save_stage": None,
    "record": False,
    "record_every": 2,
    "video_tag": "recording",
    "video_output": None,
    "video_crf": 12,
    "video_preset": "slow",
    "wandb": False,
    "wandb_project": "omnidrones",
    "wandb_entity": None,
    "wandb_name": None,
    "wandb_mode": "online",
    "wandb_run_id": None,
    "device": None,
}
DEFAULT_REPLAY_CONFIG = TRAINING_DIR / "cfg" / "replay.yaml"


def load_runtime_config(config_path: Path) -> dict:
    try:
        from hydra import compose, initialize_config_dir
        from omegaconf import OmegaConf
    except ImportError as exc:
        raise RuntimeError("Hydra/OmegaConf is required to load replay config files.") from exc

    resolved_path = config_path.expanduser().resolve()
    if not resolved_path.is_file():
        raise FileNotFoundError(f"Config file not found: {resolved_path}")

    with initialize_config_dir(config_dir=str(resolved_path.parent), version_base=None):
        cfg = compose(config_name=resolved_path.stem)
    return OmegaConf.to_container(cfg, resolve=True)


def get_nested(mapping: dict, *keys: str):
    value = mapping
    for key in keys:
        if not isinstance(value, dict):
            return None
        value = value.get(key)
        if value is None:
            return None
    return value


def first_non_none(*values):
    for value in values:
        if value is not None:
            return value
    return None


def config_arg_defaults(config: dict) -> dict:
    replay_cfg = get_nested(config, "replay") or {}

    return {
        "json": first_non_none(replay_cfg.get("json"), config.get("json")),
        "headless": first_non_none(replay_cfg.get("headless"), config.get("headless")),
        "speed": replay_cfg.get("speed"),
        "loop": replay_cfg.get("loop"),
        "anti_aliasing": first_non_none(replay_cfg.get("anti_aliasing"), get_nested(config, "viewer", "anti_aliasing")),
        "drone_model": first_non_none(replay_cfg.get("drone_model"), get_nested(config, "drone", "model_name")),
        "sim_dt": first_non_none(replay_cfg.get("sim_dt"), get_nested(config, "sim", "dt")),
        "ground_size": replay_cfg.get("ground_size"),
        "camera_mode": replay_cfg.get("camera_mode"),
        "camera_margin": replay_cfg.get("camera_margin"),
        "camera_fov_deg": replay_cfg.get("camera_fov_deg"),
        "camera_eye": first_non_none(replay_cfg.get("camera_eye"), get_nested(config, "viewer", "eye")),
        "camera_lookat": first_non_none(replay_cfg.get("camera_lookat"), get_nested(config, "viewer", "lookat")),
        "resolution": first_non_none(replay_cfg.get("resolution"), get_nested(config, "viewer", "resolution")),
        "save_stage": replay_cfg.get("save_stage"),
        "record": replay_cfg.get("record"),
        "record_every": replay_cfg.get("record_every"),
        "video_tag": replay_cfg.get("video_tag"),
        "video_output": replay_cfg.get("video_output"),
        "video_crf": replay_cfg.get("video_crf"),
        "video_preset": replay_cfg.get("video_preset"),
        "wandb": replay_cfg.get("wandb"),
        "wandb_project": first_non_none(replay_cfg.get("wandb_project"), get_nested(config, "wandb", "project")),
        "wandb_entity": first_non_none(replay_cfg.get("wandb_entity"), get_nested(config, "wandb", "entity")),
        "wandb_name": first_non_none(replay_cfg.get("wandb_name"), get_nested(config, "wandb", "name")),
        "wandb_mode": first_non_none(replay_cfg.get("wandb_mode"), get_nested(config, "wandb", "mode")),
        "wandb_run_id": first_non_none(replay_cfg.get("wandb_run_id"), get_nested(config, "wandb", "run_id")),
        "device": first_non_none(replay_cfg.get("device"), config.get("device"), get_nested(config, "sim", "device")),
    }


def build_parser(defaults: dict) -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Replay Primitive-Planner scenario_data.json with NavRL OmniDrones",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--config", type=str, default=defaults["config"], help="Optional YAML/Hydra config file, for example training/cfg/train.yaml")
    parser.add_argument("--json", type=str, default=defaults["json"], help="Path to scenario_data.json")
    parser.add_argument("--headless", action=argparse.BooleanOptionalAction, default=defaults["headless"], help="Run headless")
    parser.add_argument("--speed", type=float, default=defaults["speed"], help="Playback speed multiplier")
    parser.add_argument("--loop", action=argparse.BooleanOptionalAction, default=defaults["loop"], help="Loop playback")
    parser.add_argument("--anti-aliasing", type=int, default=defaults["anti_aliasing"], help="Viewport anti-aliasing level")
    parser.add_argument("--drone-model", type=str, default=defaults["drone_model"], help="OmniDrones multirotor model")
    parser.add_argument("--sim-dt", type=float, default=defaults["sim_dt"], help="Physics and rendering dt")
    parser.add_argument("--device", type=str, default=defaults["device"], help="Simulation device. Defaults to config value, otherwise auto-detect.")
    parser.add_argument("--ground-size", type=float, default=defaults["ground_size"], help="Ground plane size in meters")
    parser.add_argument("--camera-mode", type=str, default=defaults["camera_mode"], choices=("fit_topdown", "manual"), help="Use an automatic top-down scene fit or the manual camera coordinates below")
    parser.add_argument("--camera-margin", type=float, default=defaults["camera_margin"], help="Extra margin applied when fitting the top-down camera")
    parser.add_argument("--camera-fov-deg", type=float, default=defaults["camera_fov_deg"], help="Vertical camera field of view used for top-down fitting")
    parser.add_argument("--camera-eye", nargs=3, type=float, default=defaults["camera_eye"], help="Viewer camera eye")
    parser.add_argument("--camera-lookat", nargs=3, type=float, default=defaults["camera_lookat"], help="Viewer camera look-at")
    parser.add_argument("--resolution", nargs=2, type=int, default=defaults["resolution"], help="Render/video resolution")
    parser.add_argument("--save-stage", type=str, default=defaults["save_stage"], help="Optional .usd/.usda path to save generated stage")
    parser.add_argument("--record", action=argparse.BooleanOptionalAction, default=defaults["record"], help="Capture viewport frames during replay")
    parser.add_argument("--record-every", type=int, default=defaults["record_every"], help="Capture every N sim steps")
    parser.add_argument("--video-tag", type=str, default=defaults["video_tag"], help="WandB/local video tag")
    parser.add_argument("--video-output", type=str, default=defaults["video_output"], help="Optional local mp4 output path")
    parser.add_argument("--video-crf", type=int, default=defaults["video_crf"], help="MP4 quality setting for libx264. Lower is higher quality.")
    parser.add_argument("--video-preset", type=str, default=defaults["video_preset"], help="FFmpeg/libx264 preset used for exported video.")
    parser.add_argument("--wandb", action=argparse.BooleanOptionalAction, default=defaults["wandb"], help="Log replay metadata and video to Weights & Biases")
    parser.add_argument("--wandb-project", type=str, default=defaults["wandb_project"], help="WandB project name")
    parser.add_argument("--wandb-entity", type=str, default=defaults["wandb_entity"], help="WandB entity")
    parser.add_argument("--wandb-name", type=str, default=defaults["wandb_name"], help="WandB run name")
    parser.add_argument("--wandb-mode", type=str, default=defaults["wandb_mode"], choices=("online", "offline", "disabled"), help="WandB logging mode")
    parser.add_argument("--wandb-run-id", type=str, default=defaults["wandb_run_id"], help="Optional WandB run id to resume")
    return parser


def parse_args() -> argparse.Namespace:
    bootstrap_parser = argparse.ArgumentParser(add_help=False)
    bootstrap_parser.add_argument(
        "--config",
        type=str,
        default=str(DEFAULT_REPLAY_CONFIG) if DEFAULT_REPLAY_CONFIG.is_file() else None,
    )
    bootstrap_args, _ = bootstrap_parser.parse_known_args()

    defaults = DEFAULT_ARGS.copy()
    if bootstrap_args.config is not None:
        config_path = Path(bootstrap_args.config)
        defaults.update({k: v for k, v in config_arg_defaults(load_runtime_config(config_path)).items() if v is not None})
        defaults["config"] = str(config_path.expanduser().resolve())

    parser = build_parser(defaults)
    args = parser.parse_args()
    if args.json is None:
        parser.error("Scenario JSON path is required. Pass --json or set replay.json/json in --config.")
    if len(args.camera_eye) != 3:
        parser.error("--camera-eye must have exactly 3 values.")
    if len(args.camera_lookat) != 3:
        parser.error("--camera-lookat must have exactly 3 values.")
    if len(args.resolution) != 2:
        parser.error("--resolution must have exactly 2 values.")
    if args.camera_margin <= 0.0:
        parser.error("--camera-margin must be positive.")
    if not 1.0 < args.camera_fov_deg < 179.0:
        parser.error("--camera-fov-deg must be between 1 and 179.")
    return args


def load_scenario(json_path: Path) -> dict:
    with json_path.open("r", encoding="utf-8") as f:
        return json.load(f)


def interp_array(ts: np.ndarray, values: np.ndarray, t: float) -> np.ndarray:
    if len(ts) == 0:
        return np.zeros(values.shape[-1], dtype=float)
    if t <= ts[0]:
        return values[0]
    if t >= ts[-1]:
        return values[-1]
    idx = np.searchsorted(ts, t, side="right") - 1
    idx = max(0, min(idx, len(ts) - 2))
    dt = max(float(ts[idx + 1] - ts[idx]), 1e-9)
    alpha = (t - ts[idx]) / dt
    return values[idx] * (1.0 - alpha) + values[idx + 1] * alpha


def yaw_from_velocity(vel: np.ndarray, fallback_yaw: float) -> float:
    if np.linalg.norm(vel[:2]) < 1e-5:
        return fallback_yaw
    return math.atan2(float(vel[1]), float(vel[0]))


def scenario_duration(drones: list[dict]) -> float:
    duration = 0.0
    for drone in drones:
        traj = drone.get("trajectory")
        if traj and traj.get("timestamps"):
            duration = max(duration, float(traj["timestamps"][-1]))
    return max(duration, 0.1)


def resolve_sim_device(requested_device: str | None) -> str:
    if requested_device is None:
        return "cuda" if torch.cuda.is_available() else "cpu"
    if requested_device.startswith("cuda") and not torch.cuda.is_available():
        print(f"Requested device '{requested_device}' but CUDA is unavailable; falling back to cpu.")
        return "cpu"
    return requested_device


def resolve_drone_model_name(requested_name: str, registry: dict) -> str:
    if requested_name in registry:
        return requested_name

    normalized = requested_name.lower()
    for model_name in registry:
        if model_name.lower() == normalized:
            return model_name

    available = ", ".join(sorted(registry))
    raise KeyError(f"Unknown drone model '{requested_name}'. Available models: {available}")


def extract_rgb_frame(rgb_annotator) -> np.ndarray | None:
    rgb_data = rgb_annotator.get_data()
    if rgb_data is None or not hasattr(rgb_data, "shape"):
        return None
    frame = np.frombuffer(rgb_data, dtype=np.uint8).reshape(*rgb_data.shape)
    return np.ascontiguousarray(frame[..., :3])


def build_wandb_run_name(base_name: str | None) -> str:
    timestamp = datetime.datetime.now().strftime("%m-%d_%H-%M")
    prefix = base_name or "scenario_replay"
    return f"{prefix}_{timestamp}"


def _get_obstacle_value(obstacle: dict, *keys: str, default=None):
    for key in keys:
        if key in obstacle and obstacle[key] is not None:
            return obstacle[key]
    if default is not None:
        return default
    raise KeyError(f"Missing obstacle keys {keys}")


def extract_box_obstacles(scenario: dict) -> tuple[list[dict], list[str]]:
    obstacles = []
    raw_types = []
    supported_types = {"box", "cube", "cuboid", "obb", "static_box", "static_obstacle"}

    for raw_obstacle in scenario.get("obstacles", []):
        if not isinstance(raw_obstacle, dict):
            continue

        raw_type = raw_obstacle.get("type")
        if raw_type is not None:
            raw_types.append(str(raw_type))

        normalized_type = str(raw_type).strip().lower() if raw_type is not None else "box"
        if normalized_type not in supported_types and not any(
            key in raw_obstacle for key in ("size_x", "x_width", "width", "dx")
        ):
            continue

        try:
            x = float(_get_obstacle_value(raw_obstacle, "x", "center_x", "cx"))
            y = float(_get_obstacle_value(raw_obstacle, "y", "center_y", "cy"))
            z = float(_get_obstacle_value(raw_obstacle, "z", "center_z", "cz"))
            size_x = float(_get_obstacle_value(raw_obstacle, "size_x", "x_width", "width", "dx"))
            size_y = float(_get_obstacle_value(raw_obstacle, "size_y", "y_width", "length", "dy"))
            size_z = float(_get_obstacle_value(raw_obstacle, "size_z", "z_width", "height", "dz"))
            yaw = float(_get_obstacle_value(raw_obstacle, "yaw", "angle", "heading", default=0.0))
        except (KeyError, TypeError, ValueError):
            continue

        obstacles.append(
            {
                "x": x,
                "y": y,
                "z": z,
                "size_x": size_x,
                "size_y": size_y,
                "size_z": size_z,
                "yaw": yaw,
            }
        )

    return obstacles, sorted(set(raw_types))


def compute_scene_bounds(obstacles: list[dict], track_data: list[dict]) -> tuple[float, float, float, float, float]:
    x_mins = []
    x_maxs = []
    y_mins = []
    y_maxs = []
    z_max = 0.0

    for obs in obstacles:
        x = float(obs["x"])
        y = float(obs["y"])
        z = float(obs["z"])
        size_x = float(obs["size_x"])
        size_y = float(obs["size_y"])
        size_z = float(obs["size_z"])
        yaw = float(obs.get("yaw", 0.0))
        cos_yaw = abs(math.cos(yaw))
        sin_yaw = abs(math.sin(yaw))
        half_x = 0.5 * (cos_yaw * size_x + sin_yaw * size_y)
        half_y = 0.5 * (sin_yaw * size_x + cos_yaw * size_y)
        x_mins.append(x - half_x)
        x_maxs.append(x + half_x)
        y_mins.append(y - half_y)
        y_maxs.append(y + half_y)
        z_max = max(z_max, z + 0.5 * size_z)

    for track in track_data:
        positions = track["positions"]
        if len(positions) == 0:
            continue
        x_mins.append(float(np.min(positions[:, 0])))
        x_maxs.append(float(np.max(positions[:, 0])))
        y_mins.append(float(np.min(positions[:, 1])))
        y_maxs.append(float(np.max(positions[:, 1])))
        z_max = max(z_max, float(np.max(positions[:, 2])))

    if not x_mins:
        return (-10.0, 10.0, -10.0, 10.0, 10.0)

    return min(x_mins), max(x_maxs), min(y_mins), max(y_maxs), z_max


def compute_camera_pose(
    args: argparse.Namespace, obstacles: list[dict], track_data: list[dict]
) -> tuple[tuple[float, float, float], tuple[float, float, float]]:
    if args.camera_mode == "manual":
        return tuple(args.camera_eye), tuple(args.camera_lookat)

    x_min, x_max, y_min, y_max, z_max = compute_scene_bounds(obstacles, track_data)
    center_x = 0.5 * (x_min + x_max)
    center_y = 0.5 * (y_min + y_max)
    scene_width = max(1.0, x_max - x_min)
    scene_height = max(1.0, y_max - y_min)
    aspect = max(float(args.resolution[0]) / float(args.resolution[1]), 1e-6)
    tan_half_fov = math.tan(math.radians(args.camera_fov_deg) * 0.5)
    fit_height = 0.5 * scene_height / tan_half_fov
    fit_width = 0.5 * scene_width / (aspect * tan_half_fov)
    eye_z = max(max(fit_height, fit_width) * args.camera_margin, z_max + 6.0)
    return (center_x, center_y, eye_z), (center_x, center_y, 0.0)


def main() -> None:
    args = parse_args()
    scenario_path = Path(args.json).expanduser().resolve()
    scenario = load_scenario(scenario_path)
    obstacles, obstacle_types = extract_box_obstacles(scenario)

    from omni.isaac.kit import SimulationApp

    app_experience = None
    if "EXP_PATH" in os.environ:
        app_experience = f"{os.environ['EXP_PATH']}/omni.isaac.sim.python.kit"

    simulation_app = (
        SimulationApp({"headless": args.headless, "anti_aliasing": args.anti_aliasing}, experience=app_experience)
        if app_experience
        else SimulationApp({"headless": args.headless, "anti_aliasing": args.anti_aliasing})
    )

    try:
        import omni
        import omni.isaac.orbit.sim as sim_utils
        from omni.isaac.orbit.assets import RigidObject, RigidObjectCfg
        from omni.isaac.core.simulation_context import SimulationContext
        from omni.isaac.core.utils.extensions import enable_extension
        from omni.isaac.core.utils.viewports import set_camera_view
        from omni_drones.controllers import LeePositionController
        from omni_drones.robots.drone import MultirotorBase
        from omni_drones.utils.torch import euler_to_quaternion

        if args.record or not args.headless:
            enable_extension("omni.kit.viewport.rtx")
            enable_extension("omni.kit.viewport.pxr")
            enable_extension("omni.kit.viewport.bundle")
            enable_extension("omni.replicator.isaac")
            import omni.replicator.core as rep

        args.drone_model = resolve_drone_model_name(args.drone_model, MultirotorBase.REGISTRY)
        sim_device = resolve_sim_device(args.device)
        run_name = build_wandb_run_name(args.wandb_name)

        wandb_run = None
        if args.wandb:
            import wandb

            init_kwargs = {
                "project": args.wandb_project,
                "entity": args.wandb_entity,
                "name": run_name,
                "mode": args.wandb_mode,
                "config": {
                    "json": str(scenario_path),
                    "speed": args.speed,
                    "loop": args.loop,
                    "drone_model": args.drone_model,
                    "sim_dt": args.sim_dt,
                    "device": sim_device,
                    "record": args.record,
                    "record_every": args.record_every,
                    "resolution": list(args.resolution),
                    "video_crf": args.video_crf,
                    "video_preset": args.video_preset,
                },
            }
            if args.wandb_run_id is not None:
                init_kwargs["id"] = args.wandb_run_id
                init_kwargs["resume"] = "allow"
            wandb_run = wandb.init(**init_kwargs)

        sim = SimulationContext(
            stage_units_in_meters=1.0,
            physics_dt=args.sim_dt,
            rendering_dt=args.sim_dt,
            backend="torch",
            device=sim_device,
        )
        stage = sim.stage
        sim_utils.GroundPlaneCfg(color=(0.1, 0.1, 0.1), size=(args.ground_size, args.ground_size)).func(
            "/World/defaultGroundPlane", sim_utils.GroundPlaneCfg(color=(0.1, 0.1, 0.1), size=(args.ground_size, args.ground_size)), translation=(0, 0, 0.01)
        )
        sim_utils.DistantLightCfg(color=(0.8, 0.8, 0.8), intensity=3500.0).func(
            "/World/Light", sim_utils.DistantLightCfg(color=(0.8, 0.8, 0.8), intensity=3500.0), translation=(1.0, 0.0, 10.0)
        )
        sim_utils.DomeLightCfg(color=(0.25, 0.25, 0.30), intensity=1500.0).func(
            "/World/SkyLight", sim_utils.DomeLightCfg(color=(0.25, 0.25, 0.30), intensity=1500.0)
        )

        stage.DefinePrim("/World/Scenario", "Xform")
        stage.DefinePrim("/World/Scenario/Obstacles", "Xform")

        static_obstacles = []
        static_obstacle_states = []

        for idx, obs in enumerate(obstacles):
            prim_path = f"/World/Scenario/Obstacles/Obstacle_{idx:03d}"
            cap_path = f"/World/Scenario/Obstacles/ObstacleCap_{idx:03d}"
            yaw = float(obs.get("yaw", 0.0))
            size_x = float(obs["size_x"])
            size_y = float(obs["size_y"])
            size_z = float(obs["size_z"])

            obstacle_cfg = RigidObjectCfg(
                prim_path=prim_path,
                spawn=sim_utils.CuboidCfg(
                    size=(size_x, size_y, size_z),
                    rigid_props=sim_utils.RigidBodyPropertiesCfg(
                        rigid_body_enabled=True,
                        kinematic_enabled=True,
                        disable_gravity=True,
                    ),
                    mass_props=sim_utils.MassPropertiesCfg(mass=1.0),
                    collision_props=sim_utils.CollisionPropertiesCfg(collision_enabled=False),
                    visual_material=sim_utils.PreviewSurfaceCfg(
                        diffuse_color=(0.90, 0.73, 0.22),
                        emissive_color=(0.08, 0.06, 0.02),
                        roughness=0.35,
                        metallic=0.05,
                        opacity=0.42,
                    ),
                ),
                init_state=RigidObjectCfg.InitialStateCfg(
                    pos=(float(obs["x"]), float(obs["y"]), float(obs["z"])),
                    rot=(math.cos(yaw * 0.5), 0.0, 0.0, math.sin(yaw * 0.5)),
                ),
            )

            cap_thickness = min(0.08, max(0.04, size_z * 0.08))
            cap_z = float(obs["z"]) + 0.5 * size_z + 0.5 * cap_thickness
            cap_cfg = RigidObjectCfg(
                prim_path=cap_path,
                spawn=sim_utils.CuboidCfg(
                    size=(size_x, size_y, cap_thickness),
                    rigid_props=sim_utils.RigidBodyPropertiesCfg(
                        rigid_body_enabled=True,
                        kinematic_enabled=True,
                        disable_gravity=True,
                    ),
                    mass_props=sim_utils.MassPropertiesCfg(mass=1.0),
                    collision_props=sim_utils.CollisionPropertiesCfg(collision_enabled=False),
                    visual_material=sim_utils.PreviewSurfaceCfg(
                        diffuse_color=(1.0, 0.42, 0.10),
                        emissive_color=(0.35, 0.10, 0.03),
                        roughness=0.15,
                        metallic=0.0,
                        opacity=1.0,
                    ),
                ),
                init_state=RigidObjectCfg.InitialStateCfg(
                    pos=(float(obs["x"]), float(obs["y"]), cap_z),
                    rot=(math.cos(yaw * 0.5), 0.0, 0.0, math.sin(yaw * 0.5)),
                ),
            )

            static_obstacles.append(RigidObject(cfg=obstacle_cfg))
            static_obstacle_states.append(
                [
                    float(obs["x"]),
                    float(obs["y"]),
                    float(obs["z"]),
                    math.cos(yaw * 0.5),
                    0.0,
                    0.0,
                    math.sin(yaw * 0.5),
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                ]
            )

            static_obstacles.append(RigidObject(cfg=cap_cfg))
            static_obstacle_states.append(
                [
                    float(obs["x"]),
                    float(obs["y"]),
                    cap_z,
                    math.cos(yaw * 0.5),
                    0.0,
                    0.0,
                    math.sin(yaw * 0.5),
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                ]
            )

        drones_with_traj = [d for d in scenario.get("drones", []) if d.get("trajectory")]
        if not drones_with_traj:
            raise RuntimeError("No drones with trajectories found in scenario JSON.")

        drone_cls = MultirotorBase.REGISTRY[args.drone_model]
        drone = drone_cls()

        start_positions = []
        track_data = []
        init_yaws = []
        for drone_data in drones_with_traj:
            traj = drone_data["trajectory"]
            ts = np.array(traj["timestamps"], dtype=float)
            pos = np.array(traj["positions"], dtype=float)
            vel = np.array(traj["velocities"], dtype=float)
            if len(ts) == 0:
                continue
            start_positions.append(tuple(pos[0].tolist()))
            init_yaw = yaw_from_velocity(vel[0], 0.0)
            init_yaws.append(init_yaw)
            track_data.append(
                {
                    "id": int(drone_data["id"]),
                    "timestamps": ts,
                    "positions": pos,
                    "velocities": vel,
                    "fallback_yaw": init_yaw,
                }
            )

        if not track_data:
            raise RuntimeError("No non-empty trajectories found in scenario JSON.")

        drone.spawn(translations=start_positions)
        sim.reset()
        drone.initialize()

        n = len(track_data)
        if static_obstacles:
            obstacle_state_tensor = torch.tensor(static_obstacle_states, dtype=torch.float32, device=sim.device)
            for obstacle_asset, obstacle_state in zip(static_obstacles, obstacle_state_tensor):
                obstacle_asset.write_root_state_to_sim(obstacle_state.unsqueeze(0))
                obstacle_asset.write_data_to_sim()
                obstacle_asset.update(args.sim_dt)

        init_pos_np = np.stack([track["positions"][0] for track in track_data], axis=0)
        init_pos = torch.tensor(init_pos_np, dtype=torch.float32, device=sim.device)
        init_rpy = torch.zeros((n, 3), dtype=torch.float32, device=sim.device)
        init_rpy[:, 2] = torch.tensor(init_yaws, dtype=torch.float32, device=sim.device)
        init_rot = euler_to_quaternion(init_rpy)
        init_vels = torch.zeros((n, 6), dtype=torch.float32, device=sim.device)

        drone.set_world_poses(init_pos, init_rot)
        drone.set_velocities(init_vels)
        sim._physics_sim_view.flush()

        controller = LeePositionController(g=9.81, uav_params=drone.params).to(sim.device)
        render_product = None
        rgb_annotator = None
        captured_frames = []
        camera_eye, camera_lookat = compute_camera_pose(args, obstacles, track_data)
        set_camera_view(eye=camera_eye, target=camera_lookat)

        if args.record:
            render_resolution = tuple(int(v) for v in args.resolution)
            render_product = rep.create.render_product("/OmniverseKit_Persp", render_resolution)
            rgb_annotator = rep.AnnotatorRegistry.get_annotator("rgb", device="cpu")
            rgb_annotator.attach([render_product])
            sim.render()

        if args.save_stage:
            save_path = str(Path(args.save_stage).expanduser().resolve())
            omni.usd.get_context().save_as_stage(save_path)
            print(f"Saved generated stage to {save_path}")

        total_duration = scenario_duration(drones_with_traj)
        print(f"Loaded scenario: {scenario_path}")
        if args.config:
            print(f"Loaded replay defaults from config: {Path(args.config).expanduser().resolve()}")
        print(
            f"Loaded {len(obstacles)} replay obstacles."
            + (f" Raw obstacle types: {', '.join(obstacle_types)}" if obstacle_types else "")
        )
        print(f"Replaying {n} drones with total duration {total_duration:.2f}s at speed {args.speed:.2f}x")
        print(
            "Camera pose:"
            f" mode={args.camera_mode}"
            f" eye=({camera_eye[0]:.2f}, {camera_eye[1]:.2f}, {camera_eye[2]:.2f})"
            f" lookat=({camera_lookat[0]:.2f}, {camera_lookat[1]:.2f}, {camera_lookat[2]:.2f})"
        )
        sim.play()

        step_count = 0
        while simulation_app.is_running():
            if sim.is_stopped():
                break
            if not sim.is_playing():
                sim.render()
                continue

            elapsed = step_count * args.sim_dt * args.speed
            sim_t = elapsed % total_duration if args.loop else min(elapsed, total_duration)

            target_pos = np.stack([interp_array(track["timestamps"], track["positions"], sim_t) for track in track_data], axis=0)
            target_vel = np.stack([interp_array(track["timestamps"], track["velocities"], sim_t) for track in track_data], axis=0)
            target_yaw = np.array([
                yaw_from_velocity(target_vel[i], track_data[i]["fallback_yaw"]) for i in range(n)
            ], dtype=np.float32)

            drone_state = drone.get_state()[..., :13].squeeze(0)
            action = controller(
                drone_state,
                target_pos=torch.tensor(target_pos, dtype=torch.float32, device=sim.device),
                target_yaw=torch.tensor(target_yaw, dtype=torch.float32, device=sim.device),
            )
            drone.apply_action(action)
            sim.step(render=True)
            step_count += 1

            if rgb_annotator is not None and (step_count % max(1, args.record_every) == 0):
                frame = extract_rgb_frame(rgb_annotator)
                if frame is not None:
                    captured_frames.append(frame)

            if not args.loop and elapsed >= total_duration:
                for _ in range(60):
                    if not simulation_app.is_running():
                        break
                    sim.step(render=True)
                break

        if captured_frames:
            frames_np = np.stack(captured_frames, axis=0)
            frames = torch.from_numpy(frames_np.copy())
            fps = max(1, int(round(1.0 / (args.sim_dt * max(1, args.record_every)))))
            print(f"Captured {len(captured_frames)} frames at resolution {frames_np.shape[2]}x{frames_np.shape[1]}.")
            if args.video_output:
                from torchvision.io import write_video

                video_path = str(Path(args.video_output).expanduser().resolve())
                write_video(
                    video_path,
                    frames,
                    fps=fps,
                    video_codec="libx264",
                    options={
                        "crf": str(args.video_crf),
                        "preset": args.video_preset,
                        "pix_fmt": "yuv420p",
                    },
                )
                print(f"Saved replay video to {video_path}")
            if wandb_run is not None:
                import wandb

                wandb_run.log(
                    {
                        "scenario_duration": total_duration,
                        "num_drones": n,
                        args.video_tag: wandb.Video(np.transpose(frames_np, (0, 3, 1, 2)), fps=fps, format="mp4"),
                    }
                )
        elif wandb_run is not None:
            if args.record:
                print("Recording was enabled, but no frames were captured.")
            wandb_run.log(
                {
                    "scenario_duration": total_duration,
                    "num_drones": n,
                }
            )

    finally:
        try:
            if "wandb_run" in locals() and wandb_run is not None:
                wandb_run.finish()
        finally:
            pass
        simulation_app.close()


if __name__ == "__main__":
    main()
