#!/usr/bin/env python3
"""
Replay Primitive-Planner scenario_data.json in the NavRL Isaac Sim / OmniDrones stack.

This script is additive: it does not modify NavRL environment code.
It loads the JSON scene generated by Primitive-Planner, spawns static box obstacles,
creates one OmniDrones multirotor per valid trajectory, and tracks the logged path
with LeePositionController.

Example:
  /home/haoyus/projects/NavRL/isaac-sim/python.sh \
    /home/haoyus/projects/NavRL/NavRL-code/NavRL/isaac-training/training/scripts/scenario_json_replay.py \
    --json /abs/path/to/scenario_data.json

Notes:
- Tested for the NavRL layout that vendors OmniDrones and Orbit under `isaac-training/third_party`.
- The script uses the same Hummingbird multirotor class NavRL trains with by default.
- Obstacles are visualized as static USD cubes; drones are physically simulated and
  commanded to track the reference path.
"""

from __future__ import annotations

import argparse
import json
import math
import os
import sys
import time
from pathlib import Path

import numpy as np
import torch


SCRIPT_DIR = Path(__file__).resolve().parent
TRAINING_DIR = SCRIPT_DIR.parent
ISAAC_TRAINING_DIR = TRAINING_DIR.parent
THIRD_PARTY_DIR = ISAAC_TRAINING_DIR / "third_party"
OMNIDRONES_DIR = THIRD_PARTY_DIR / "OmniDrones"
ORBIT_SOURCE_DIR = THIRD_PARTY_DIR / "orbit" / "source"

for path in (SCRIPT_DIR, TRAINING_DIR, OMNIDRONES_DIR):
    path_str = str(path)
    if path_str not in sys.path:
        sys.path.insert(0, path_str)
for ext_dir in ORBIT_SOURCE_DIR.glob("extensions/*"):
    path_str = str(ext_dir)
    if path_str not in sys.path:
        sys.path.insert(0, path_str)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Replay Primitive-Planner scenario_data.json with NavRL OmniDrones",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--json", required=True, help="Path to scenario_data.json")
    parser.add_argument("--headless", action="store_true", help="Run headless")
    parser.add_argument("--speed", type=float, default=1.0, help="Playback speed multiplier")
    parser.add_argument("--loop", action="store_true", help="Loop playback")
    parser.add_argument("--drone-model", type=str, default="Hummingbird", help="OmniDrones multirotor model")
    parser.add_argument("--sim-dt", type=float, default=0.01, help="Physics and rendering dt")
    parser.add_argument("--ground-size", type=float, default=120.0, help="Ground plane size in meters")
    parser.add_argument("--camera-eye", nargs=3, type=float, default=(18.0, -18.0, 16.0), help="Viewer camera eye")
    parser.add_argument("--camera-lookat", nargs=3, type=float, default=(0.0, 0.0, 0.0), help="Viewer camera look-at")
    parser.add_argument("--save-stage", type=str, default=None, help="Optional .usd/.usda path to save generated stage")
    parser.add_argument("--record", action="store_true", help="Capture viewport frames during replay")
    parser.add_argument("--record-every", type=int, default=2, help="Capture every N sim steps")
    parser.add_argument("--video-tag", type=str, default="recording", help="WandB/local video tag")
    parser.add_argument("--video-output", type=str, default=None, help="Optional local mp4 output path")
    parser.add_argument("--wandb", action="store_true", help="Log replay metadata and video to Weights & Biases")
    parser.add_argument("--wandb-project", type=str, default="omnidrones", help="WandB project name")
    parser.add_argument("--wandb-entity", type=str, default=None, help="WandB entity")
    parser.add_argument("--wandb-name", type=str, default=None, help="WandB run name")
    parser.add_argument("--wandb-mode", type=str, default="online", choices=("online", "offline", "disabled"), help="WandB logging mode")
    parser.add_argument("--wandb-run-id", type=str, default=None, help="Optional WandB run id to resume")
    return parser.parse_args()


def load_scenario(json_path: Path) -> dict:
    with json_path.open("r", encoding="utf-8") as f:
        return json.load(f)


def interp_array(ts: np.ndarray, values: np.ndarray, t: float) -> np.ndarray:
    if len(ts) == 0:
        return np.zeros(values.shape[-1], dtype=float)
    if t <= ts[0]:
        return values[0]
    if t >= ts[-1]:
        return values[-1]
    idx = np.searchsorted(ts, t, side="right") - 1
    idx = max(0, min(idx, len(ts) - 2))
    dt = max(float(ts[idx + 1] - ts[idx]), 1e-9)
    alpha = (t - ts[idx]) / dt
    return values[idx] * (1.0 - alpha) + values[idx + 1] * alpha


def yaw_from_velocity(vel: np.ndarray, fallback_yaw: float) -> float:
    if np.linalg.norm(vel[:2]) < 1e-5:
        return fallback_yaw
    return math.atan2(float(vel[1]), float(vel[0]))


def scenario_duration(drones: list[dict]) -> float:
    duration = 0.0
    for drone in drones:
        traj = drone.get("trajectory")
        if traj and traj.get("timestamps"):
            duration = max(duration, float(traj["timestamps"][-1]))
    return max(duration, 0.1)


def main() -> None:
    args = parse_args()
    scenario_path = Path(args.json).expanduser().resolve()
    scenario = load_scenario(scenario_path)

    from omni.isaac.kit import SimulationApp

    app_experience = None
    if "EXP_PATH" in os.environ:
        app_experience = f"{os.environ['EXP_PATH']}/omni.isaac.sim.python.kit"

    simulation_app = (
        SimulationApp({"headless": args.headless, "anti_aliasing": 1}, experience=app_experience)
        if app_experience
        else SimulationApp({"headless": args.headless, "anti_aliasing": 1})
    )

    try:
        import omni
        import omni.isaac.orbit.sim as sim_utils
        from omni.isaac.core.simulation_context import SimulationContext
        from omni.isaac.core.utils.viewports import set_camera_view
        from omni_drones.controllers import LeePositionController
        from omni_drones.robots.drone import MultirotorBase
        from omni_drones.sensors.camera import Camera, PinholeCameraCfg
        from omni_drones.utils.torch import euler_to_quaternion
        from pxr import Gf, Sdf, UsdGeom, UsdShade

        wandb_run = None
        if args.wandb:
            import datetime
            import wandb

            run_name = args.wandb_name or f"scenario-replay/{datetime.datetime.now().strftime('%m-%d_%H-%M')}"
            init_kwargs = {
                "project": args.wandb_project,
                "entity": args.wandb_entity,
                "name": run_name,
                "mode": args.wandb_mode,
                "config": {
                    "json": str(scenario_path),
                    "speed": args.speed,
                    "loop": args.loop,
                    "drone_model": args.drone_model,
                    "sim_dt": args.sim_dt,
                    "record": args.record,
                    "record_every": args.record_every,
                },
            }
            if args.wandb_run_id is not None:
                init_kwargs["id"] = args.wandb_run_id
                init_kwargs["resume"] = "allow"
            wandb_run = wandb.init(**init_kwargs)

        sim = SimulationContext(
            stage_units_in_meters=1.0,
            physics_dt=args.sim_dt,
            rendering_dt=args.sim_dt,
            backend="torch",
            device="cuda" if torch.cuda.is_available() else "cpu",
        )
        stage = sim.stage
        sim_utils.GroundPlaneCfg(color=(0.1, 0.1, 0.1), size=(args.ground_size, args.ground_size)).func(
            "/World/defaultGroundPlane", sim_utils.GroundPlaneCfg(color=(0.1, 0.1, 0.1), size=(args.ground_size, args.ground_size)), translation=(0, 0, 0.01)
        )
        sim_utils.DistantLightCfg(color=(0.8, 0.8, 0.8), intensity=3500.0).func(
            "/World/Light", sim_utils.DistantLightCfg(color=(0.8, 0.8, 0.8), intensity=3500.0), translation=(1.0, 0.0, 10.0)
        )
        sim_utils.DomeLightCfg(color=(0.25, 0.25, 0.30), intensity=1500.0).func(
            "/World/SkyLight", sim_utils.DomeLightCfg(color=(0.25, 0.25, 0.30), intensity=1500.0)
        )

        UsdGeom.Scope.Define(stage, "/World/Looks")

        def ensure_material(name: str, rgb: tuple[float, float, float]) -> str:
            material_path = f"/World/Looks/{name}"
            material = UsdShade.Material.Define(stage, material_path)
            shader = UsdShade.Shader.Define(stage, f"{material_path}/Shader")
            shader.CreateIdAttr("UsdPreviewSurface")
            shader.CreateInput("diffuseColor", Sdf.ValueTypeNames.Color3f).Set(Gf.Vec3f(*rgb))
            shader.CreateInput("roughness", Sdf.ValueTypeNames.Float).Set(0.45)
            material.CreateSurfaceOutput().ConnectToSource(shader.ConnectableAPI(), "surface")
            return material_path

        obstacle_material_path = ensure_material("Obstacle", (0.35, 0.35, 0.38))

        def bind_material(prim, material_path: str) -> None:
            material = UsdShade.Material.Get(stage, material_path)
            UsdShade.MaterialBindingAPI(prim).Bind(material)

        stage.DefinePrim("/World/Scenario", "Xform")
        stage.DefinePrim("/World/Scenario/Obstacles", "Xform")

        for idx, obs in enumerate(scenario.get("obstacles", [])):
            if obs.get("type") != "box":
                continue
            prim_path = f"/World/Scenario/Obstacles/Obstacle_{idx:03d}"
            cube = UsdGeom.Cube.Define(stage, prim_path)
            cube.CreateSizeAttr(1.0)
            xform = UsdGeom.XformCommonAPI(cube)
            xform.SetTranslate((float(obs["x"]), float(obs["y"]), float(obs["z"])))
            xform.SetRotate(
                (0.0, 0.0, math.degrees(float(obs.get("yaw", 0.0)))),
                UsdGeom.XformCommonAPI.RotationOrderXYZ,
            )
            xform.SetScale((float(obs["size_x"]), float(obs["size_y"]), float(obs["size_z"])))
            bind_material(cube.GetPrim(), obstacle_material_path)

        drones_with_traj = [d for d in scenario.get("drones", []) if d.get("trajectory")]
        if not drones_with_traj:
            raise RuntimeError("No drones with trajectories found in scenario JSON.")

        drone_cls = MultirotorBase.REGISTRY[args.drone_model]
        drone = drone_cls()

        start_positions = []
        track_data = []
        init_yaws = []
        for drone_data in drones_with_traj:
            traj = drone_data["trajectory"]
            ts = np.array(traj["timestamps"], dtype=float)
            pos = np.array(traj["positions"], dtype=float)
            vel = np.array(traj["velocities"], dtype=float)
            if len(ts) == 0:
                continue
            start_positions.append(tuple(pos[0].tolist()))
            init_yaw = yaw_from_velocity(vel[0], 0.0)
            init_yaws.append(init_yaw)
            track_data.append(
                {
                    "id": int(drone_data["id"]),
                    "timestamps": ts,
                    "positions": pos,
                    "velocities": vel,
                    "fallback_yaw": init_yaw,
                }
            )

        if not track_data:
            raise RuntimeError("No non-empty trajectories found in scenario JSON.")

        drone.spawn(translations=start_positions)
        sim.reset()
        drone.initialize()

        n = len(track_data)
        init_pos = torch.tensor([track["positions"][0] for track in track_data], dtype=torch.float32, device=sim.device)
        init_rpy = torch.zeros((n, 3), dtype=torch.float32, device=sim.device)
        init_rpy[:, 2] = torch.tensor(init_yaws, dtype=torch.float32, device=sim.device)
        init_rot = euler_to_quaternion(init_rpy)
        init_vels = torch.zeros((n, 6), dtype=torch.float32, device=sim.device)

        drone.set_world_poses(init_pos, init_rot)
        drone.set_velocities(init_vels)
        sim._physics_sim_view.flush()

        controller = LeePositionController(g=9.81, uav_params=drone.params).to(sim.device)
        camera_vis = None
        captured_frames = []
        if args.record:
            camera_cfg = PinholeCameraCfg(
                sensor_tick=0,
                resolution=(960, 720),
                data_types=["rgb"],
            )
            camera_vis = Camera(camera_cfg)
            camera_vis.initialize("/OmniverseKit_Persp")

        if not args.headless:
            set_camera_view(eye=args.camera_eye, target=args.camera_lookat)

        if args.save_stage:
            save_path = str(Path(args.save_stage).expanduser().resolve())
            omni.usd.get_context().save_as_stage(save_path)
            print(f"Saved generated stage to {save_path}")

        total_duration = scenario_duration(drones_with_traj)
        print(f"Loaded scenario: {scenario_path}")
        print(f"Replaying {n} drones with total duration {total_duration:.2f}s at speed {args.speed:.2f}x")

        start_wall = time.perf_counter()
        step_count = 0
        while simulation_app.is_running():
            if sim.is_stopped():
                break
            if not sim.is_playing():
                sim.render()
                continue

            elapsed = (time.perf_counter() - start_wall) * args.speed
            sim_t = elapsed % total_duration if args.loop else min(elapsed, total_duration)

            target_pos = np.stack([interp_array(track["timestamps"], track["positions"], sim_t) for track in track_data], axis=0)
            target_vel = np.stack([interp_array(track["timestamps"], track["velocities"], sim_t) for track in track_data], axis=0)
            target_yaw = np.array([
                yaw_from_velocity(target_vel[i], track_data[i]["fallback_yaw"]) for i in range(n)
            ], dtype=np.float32)

            drone_state = drone.get_state()[..., :13].squeeze(0)
            action = controller(
                drone_state,
                target_pos=torch.tensor(target_pos, dtype=torch.float32, device=sim.device),
                target_yaw=torch.tensor(target_yaw, dtype=torch.float32, device=sim.device),
            )
            drone.apply_action(action)
            sim.step(render=True)
            step_count += 1

            if camera_vis is not None and (step_count % max(1, args.record_every) == 0):
                captured_frames.append(camera_vis.get_images()["rgb"].cpu())

            if not args.loop and elapsed >= total_duration:
                for _ in range(60):
                    if not simulation_app.is_running():
                        break
                    sim.step(render=True)
                break

        if captured_frames:
            frames = torch.cat(captured_frames, dim=0).permute(0, 2, 3, 1)[..., :3].contiguous()
            fps = max(1, int(round(1.0 / (args.sim_dt * max(1, args.record_every)))))
            if args.video_output:
                from torchvision.io import write_video

                video_path = str(Path(args.video_output).expanduser().resolve())
                write_video(video_path, frames, fps=fps)
                print(f"Saved replay video to {video_path}")
            if wandb_run is not None:
                import wandb

                wandb_run.log(
                    {
                        "scenario_duration": total_duration,
                        "num_drones": n,
                        args.video_tag: wandb.Video(frames.permute(0, 3, 1, 2).numpy(), fps=fps, format="mp4"),
                    }
                )
        elif wandb_run is not None:
            wandb_run.log(
                {
                    "scenario_duration": total_duration,
                    "num_drones": n,
                }
            )

    finally:
        try:
            if "wandb_run" in locals() and wandb_run is not None:
                wandb_run.finish()
        finally:
            pass
        simulation_app.close()


if __name__ == "__main__":
    main()
